= Summary Activities During the Sprint

== MSC

- created EDR API https://github.com/tomkralidis/pygeoapi/tress/edr-api[baseline implementation in pygeoapi]
- created OGC API - Processes process to calculate wind speed from EDR API queries
  - OAProc request -> OAProc process -> EDR API query -> EDR API response -> wind speed calculation -> OAProc response
- review of OGC API - Records https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/record.yaml[record model] as part of the https://github.com/OGCMetOceanDWG/ogcapi-records-metocean-bp[MetOcean Best Practices for OGC API - Records]

== WHU

- published a serie of thematic data as “collections” on WHU EDR server for disaster analysis, such as the location of villages, schools, bridges, and paddy fields in Hainan.
- developed the "Flood Disaster Decision Support System" use case with EDR API instead of WPS/WCS/WFS to query the related data after obtaining a typhoon trajectory/corridor or flood inundation area.
- tried to support the EDR API service provided by other organizations in our demo to show interoperability, for example, query the precipitation data from the NOAA NWS EDR API server in our client.

== NOAA NWS

TBA

== IBL

TBA

== UK Met Office

TBA
